config/routes.rb
Shorty::Application.routes.draw do
  resources :urls, :only => [:show, :new, :create]

  get '/:id~' => 'urls#detail'
  get '/:id' => 'urls#show'

  root :to => redirect('/urls/new')

end

app/models/clicksource.rb
require 'geoip'

class Clicksource < ActiveRecord::Base
  validates :url_id, :presence => true
  belongs_to :url



  def city
    c = GeoIP.new('lib/GeoLiteCity.dat').city(self.ip)
    c.city_name.encode('utf-8')
  end

  def country
    c = GeoIP.new('lib/GeoLiteCity.dat').city(self.ip)
    c.country_name.encode('utf-8')
  end

end

app/models/url.rb
class Url < ActiveRecord::Base
  validates :url, :presence => true
  validates_format_of :url, :with => /^(http|https|ftp|ftps):\/\/(([a-z0-9]+\:)?[a-z0-9]+\@)?[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?$/ix, :multiline => true

  has_many :clicksources

  def short_code
    id.to_s(36)
  end

  def self.find_using_short_code!(short_code)
    find short_code.to_i(36)
  end

  def click_counter
    self.increment!(:clicks)

  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  def new
    @shortened_url = Url.new
  end

  def create
    @shortened_url = Url.new(url_params)
    if @shortened_url.save
      code = @shortened_url.short_code
      flash[:short_code] = code
      redirect_to new_url_url

    else
      render :action => "new"
    end
  end

  def show
    #@shortened_url = Url.find(params[:id])
    @shortened_url = Url.find_using_short_code!(params[:id])
    redirect_to @shortened_url.url
    @shortened_url.click_counter
    c = Clicksource.create!(:ip => request.remote_ip, :agent => request.user_agent, :url_id => @shortened_url.id, :referer => request.referer)
  end

  def detail
    my_id = params[:id]
    my_id.chomp!
    @url = Url.find_using_short_code!(my_id)
    puts @url
  end

  private

  def url_params
    params.require(:url).permit(:url, :short_code)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shorty</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar">
  <div class="navbar-inner">
    <a class="brand" href="/">Shorty the Shortener</a>
    <ul class="nav">
      <li class="active"><a href="/">Home</a></li>

    </ul>
  </div>
</div>


<div class="container">
<div class="row">
  <div class="span9">
    <% if flash[:short_code].present? %>
        <p class='shortened-link'>

          <% if request.port > 80 %>
            <% url = request.domain + ':' + request.port.to_s + '/' + flash[:short_code]%>

          <% else %>
            <% url = request.domain + '/' + flash[:short_code] %>
          <% end %>
          The shortened url is available: <h3><%= url %></h3>Copy and paste to share or click <a href="<%= request.protocol + url %>">here</a> to be redirected automatically!


        </p>
    <% end %>


    <%= yield %>

  </div>
  <div class="span3"><% if flash[:short_code].present? %>
        <img src="/statistics3.jpg"></img>
        View statistics on this url by visiting <a href="<%= request.protocol + url + '~'%>"><%= url + '~'%></a>
        <% end %>
  </div>


</div>
</div>
</body>
</html>

app/views/urls/_form.html.erb
<%= form_for @shortened_url, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :url, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :url, :class => 'text_field' %>
    </div>
  </div>

    <% if @shortened_url.errors[:url].any? %>
        <p class='error-messages'>
          The given url <%= @shortened_url.errors[:url].to_sentence %>.  *Hint - don't forget to add http://
        </p>
    <% end %>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/urls/detail.html.erb
<%- model_class = Url -%>
<% if request.port > 80 %>
    <% url = request.domain + ':' + request.port.to_s + '/' + @url.short_code%>

<% else %>
    <% url = request.domain + '/' + @url.short_code %>
<% end %>

<div class="page-header">
  <h1><%=url %></h1>
</div>



<dl class="dl-horizontal">
  <dt><strong>Shortened URL:</strong></dt>
  <dd><%= request.protocol + url %></dd>
  <dt><strong><%= model_class.human_attribute_name(:url) %>:</strong></dt>
  <dd><%= @url.url %></dd>
  <dt><strong><%= model_class.human_attribute_name(:clicks) %>:</strong></dt>
  <dd><%= @url.clicks %></dd>
</dl>

<table class="table table-condensed">
  <thead>
  <tr>
    <th>IP</th>
    <th>User Agent</th>
    <th>Time Clicked</th>
    <th>Country/City</th>
  </tr>
  </thead>
  <tbody>
  <% @url.clicksources.order("id DESC").each do |url| %>
      <tr>

        <td><%= url.ip %></td>
        <td><small><%= url.agent %></small></td>
        <td><small><%=l url.created_at %></small></td>
        <% if url.ip == '127.0.0.1' %>
        <% url.ip = '192.99.1.117'%>
        <% end %>
        <td><small><%= url.country + '/' + url.city %></small></td>
      </tr>
  <% end %>
  </tbody>
</table>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              '/', :class => 'btn'  %>

</div>

app/views/urls/edit.html.erb
<%- model_class = Url -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/urls/index.html.erb
<%- model_class = Url -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:url) %></th>
      <th><%= model_class.human_attribute_name(:clicks) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @urls.each do |url| %>
      <tr>
        <td><%= link_to url.id, url_path(url) %></td>
        <td><%= url.url %></td>
        <td><%= url.clicks %></td>
        <td><%=l url.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_url_path(url), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      url_path(url),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_url_path,
            :class => 'btn btn-primary' %>

app/views/urls/new.html.erb
<%- model_class = Url -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>